# Generated by Django 4.0.6 on 2022-07-29 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsnews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 15, 45, 48, 439569, tzinfo=utc), verbose_name='Дата Публікації'),
        ),
        migrations.AlterField(
            model_name='news',
            name='anons',
            field=models.CharField(max_length=255, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
